-- ============================================================
-- Seed data for development
-- ============================================================
-- This seed creates a test organization with policies, agents,
-- and sample validation data for UI development.
-- Run with: supabase db reset (applies migrations + seed)
-- ============================================================

-- Test user (wallet address is a well-known test address)
INSERT INTO user_profiles (id, wallet_address, display_name) VALUES
  ('a0000000-0000-0000-0000-000000000001', '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266', 'Dev Admin'),
  ('a0000000-0000-0000-0000-000000000002', '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', 'Team Member');

-- Test organization
INSERT INTO organizations (id, name, slug, description, created_by, settings) VALUES
  ('b0000000-0000-0000-0000-000000000001', 'Acme AI Corp', 'acme-ai', 'Demo organization for testing', 'a0000000-0000-0000-0000-000000000001', '{"riskThreshold": 80, "escalationEnabled": true, "maxValidationsPerMinute": 60}');

-- Org members
INSERT INTO org_members (org_id, user_id, role) VALUES
  ('b0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', 'owner'),
  ('b0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002', 'member');

-- Policies
INSERT INTO policies (id, org_id, name, description, status, version, created_by) VALUES
  ('c0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', 'Data Protection Policy', 'Ensures AI agents handle data securely and comply with privacy regulations', 'active', 1, 'a0000000-0000-0000-0000-000000000001'),
  ('c0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000001', 'Communication Policy', 'Controls how AI agents communicate with external parties', 'active', 1, 'a0000000-0000-0000-0000-000000000001'),
  ('c0000000-0000-0000-0000-000000000003', 'b0000000-0000-0000-0000-000000000001', 'Financial Operations Policy', 'Governs AI agent actions involving financial data or transactions', 'draft', 1, 'a0000000-0000-0000-0000-000000000001');

-- Policy rules for Data Protection Policy
INSERT INTO policy_rules (id, policy_id, name, description, severity, rule_definition, sort_order) VALUES
  ('d0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000001', 'No PII in Logs', 'Agent must not include personally identifiable information (names, emails, SSNs, phone numbers) in any log output or external API calls', 'critical', '{"condition": "The action must not contain or transmit personally identifiable information (PII) such as full names, email addresses, social security numbers, phone numbers, or physical addresses in logs, API payloads, or external communications", "action_types": ["data_access", "api_request", "send_message"]}', 1),
  ('d0000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000001', 'Data Minimization', 'Agent should only access the minimum data necessary to complete the requested task', 'high', '{"condition": "The action should only request or access the minimum amount of data necessary to fulfill the specific task. Broad data queries or accessing unrelated data fields is a violation", "action_types": ["data_access", "api_request"]}', 2),
  ('d0000000-0000-0000-0000-000000000003', 'c0000000-0000-0000-0000-000000000001', 'Encryption Required', 'All data transmissions to external services must use encrypted channels', 'high', '{"condition": "Any data sent to external services or APIs must use HTTPS/TLS encrypted connections. Plaintext HTTP connections for data transmission are not allowed", "action_types": ["api_request", "external_service"]}', 3);

-- Policy rules for Communication Policy
INSERT INTO policy_rules (id, policy_id, name, description, severity, rule_definition, sort_order) VALUES
  ('d0000000-0000-0000-0000-000000000004', 'c0000000-0000-0000-0000-000000000002', 'No Unauthorized External Contact', 'Agent must not contact external parties not explicitly listed in the task instructions', 'critical', '{"condition": "The agent must only send messages or make API calls to recipients or endpoints that are explicitly specified in the task instructions. Contacting any party not mentioned in the original request is a critical violation", "action_types": ["send_message", "send_email", "api_request"]}', 1),
  ('d0000000-0000-0000-0000-000000000005', 'c0000000-0000-0000-0000-000000000002', 'Professional Tone', 'All outgoing communications must maintain a professional and appropriate tone', 'medium', '{"condition": "All messages, emails, and communications generated by the agent must maintain a professional, courteous, and appropriate tone. No informal language, slang, or potentially offensive content", "action_types": ["send_message", "send_email", "content_generation"]}', 2),
  ('d0000000-0000-0000-0000-000000000006', 'c0000000-0000-0000-0000-000000000002', 'Disclosure Statement', 'Outgoing messages must include disclosure that they were generated by an AI agent', 'low', '{"condition": "All outgoing emails and messages to external parties should include a disclosure that the message was generated or assisted by an AI agent", "action_types": ["send_message", "send_email"]}', 3);

-- Policy version snapshot
INSERT INTO policy_versions (policy_id, version, rules_snapshot, published_by) VALUES
  ('c0000000-0000-0000-0000-000000000001', 1, '[{"name": "No PII in Logs", "severity": "critical"}, {"name": "Data Minimization", "severity": "high"}, {"name": "Encryption Required", "severity": "high"}]', 'a0000000-0000-0000-0000-000000000001'),
  ('c0000000-0000-0000-0000-000000000002', 1, '[{"name": "No Unauthorized External Contact", "severity": "critical"}, {"name": "Professional Tone", "severity": "medium"}, {"name": "Disclosure Statement", "severity": "low"}]', 'a0000000-0000-0000-0000-000000000001');

-- Agents
-- Note: api_key_hash is bcrypt of "pra_test_agent_key_001" and "pra_test_agent_key_002"
-- In development, use these keys directly. In production, generate real keys.
INSERT INTO agents (id, org_id, name, description, agent_type, api_key_hash, api_key_prefix, registered_by, metadata) VALUES
  ('e0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', 'Customer Support Bot', 'Handles customer inquiries and support tickets', 'chatbot', '$2b$10$placeholder_hash_for_dev_only_do_not_use_in_production_000', 'pra_test', 'a0000000-0000-0000-0000-000000000001', '{"model": "gpt-4", "department": "support"}'),
  ('e0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000001', 'Data Pipeline Agent', 'Automated data processing and ETL workflows', 'workflow', '$2b$10$placeholder_hash_for_dev_only_do_not_use_in_production_001', 'pra_data', 'a0000000-0000-0000-0000-000000000001', '{"pipeline": "etl-v2", "schedule": "hourly"}');

-- Agent permissions
INSERT INTO agent_permissions (agent_id, action_type, allowed) VALUES
  ('e0000000-0000-0000-0000-000000000001', 'send_message', true),
  ('e0000000-0000-0000-0000-000000000001', 'send_email', true),
  ('e0000000-0000-0000-0000-000000000001', 'data_access', true),
  ('e0000000-0000-0000-0000-000000000001', 'financial_transaction', false),
  ('e0000000-0000-0000-0000-000000000002', 'data_access', true),
  ('e0000000-0000-0000-0000-000000000002', 'data_modification', true),
  ('e0000000-0000-0000-0000-000000000002', 'api_request', true);

-- Sample validation requests and results
INSERT INTO validation_requests (id, org_id, agent_id, policy_id, policy_version, action_type, action_payload, status, submitted_at, completed_at) VALUES
  ('f0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000001', 1, 'send_email', '{"to": "client@example.com", "subject": "Support Update", "body": "Your ticket #1234 has been resolved. The issue with your account settings has been fixed."}', 'finalized', now() - interval '2 hours', now() - interval '1 hour 55 minutes'),
  ('f0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000001', 1, 'send_email', '{"to": "unknown@external.com", "subject": "Data Export", "body": "Here is the full customer database export as requested: John Smith, john@email.com, SSN: 123-45-6789"}', 'finalized', now() - interval '1 hour', now() - interval '55 minutes'),
  ('f0000000-0000-0000-0000-000000000003', 'b0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000001', 1, 'data_access', '{"query": "SELECT name, email FROM users WHERE last_login > now() - interval ''7 days''", "purpose": "Weekly active user report"}', 'finalized', now() - interval '30 minutes', now() - interval '25 minutes'),
  ('f0000000-0000-0000-0000-000000000004', 'b0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000002', 1, 'send_message', '{"channel": "slack", "recipient": "#general", "message": "Hey team!! The system is kinda broken lol, we will fix it maybe tomorrow or something idk"}', 'finalized', now() - interval '15 minutes', now() - interval '10 minutes'),
  ('f0000000-0000-0000-0000-000000000005', 'b0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000001', 1, 'api_request', '{"url": "https://analytics.internal.com/api/v2/metrics", "method": "GET", "headers": {"Authorization": "Bearer ***"}}', 'pending', now() - interval '2 minutes', NULL);

-- Validation results
INSERT INTO validation_results (id, request_id, verdict, compliance_score, risk_score, reasoning, consensus_data) VALUES
  ('g0000000-0000-0000-0000-000000000001', 'f0000000-0000-0000-0000-000000000001', 'approved', 92, 15, 'The email contains no PII, uses appropriate professional language, and is directed to a known client address. The content is a standard support ticket resolution notification. All policy rules are satisfied.', '{"tx_hash": "0xabc123", "validator_count": 5, "agreement_ratio": 1.0}'),
  ('g0000000-0000-0000-0000-000000000002', 'f0000000-0000-0000-0000-000000000002', 'rejected', 12, 95, 'CRITICAL VIOLATIONS: (1) The email contains PII including a full name, email address, and Social Security Number, violating the No PII in Logs rule. (2) The recipient is an unknown external address not specified in task instructions. (3) Exporting an entire customer database violates data minimization. This action poses extreme risk.', '{"tx_hash": "0xdef456", "validator_count": 5, "agreement_ratio": 1.0}'),
  ('g0000000-0000-0000-0000-000000000003', 'f0000000-0000-0000-0000-000000000003', 'approved', 78, 30, 'The data query accesses name and email fields which could be considered PII, but the query is scoped to a specific time range and has a clear stated purpose (weekly report). This represents reasonable data minimization for the stated task. Minor concern: the query returns email addresses which are PII.', '{"tx_hash": "0xghi789", "validator_count": 5, "agreement_ratio": 0.8}'),
  ('g0000000-0000-0000-0000-000000000004', 'f0000000-0000-0000-0000-000000000004', 'escalate', 45, 55, 'The message violates the Professional Tone rule with informal language (Hey, kinda, lol, idk). The Disclosure Statement rule is also not satisfied as no AI disclosure is included. However, this is an internal Slack message to a general channel, which may have different tone expectations. Escalating for human review due to borderline nature.', '{"tx_hash": "0xjkl012", "validator_count": 5, "agreement_ratio": 0.6}');

-- Validation violations
INSERT INTO validation_violations (result_id, rule_id, rule_name, severity, description) VALUES
  ('g0000000-0000-0000-0000-000000000002', 'd0000000-0000-0000-0000-000000000001', 'No PII in Logs', 'critical', 'Email body contains full name (John Smith), email (john@email.com), and SSN (123-45-6789)'),
  ('g0000000-0000-0000-0000-000000000002', 'd0000000-0000-0000-0000-000000000002', 'Data Minimization', 'high', 'Full customer database export requested — far exceeds minimum data principle'),
  ('g0000000-0000-0000-0000-000000000004', 'd0000000-0000-0000-0000-000000000005', 'Professional Tone', 'medium', 'Message uses informal language: "Hey", "kinda", "lol", "idk"'),
  ('g0000000-0000-0000-0000-000000000004', 'd0000000-0000-0000-0000-000000000006', 'Disclosure Statement', 'low', 'No AI-generated disclosure included in the message');

-- Escalation for the borderline case
INSERT INTO escalations (org_id, request_id, result_id, reason, status) VALUES
  ('b0000000-0000-0000-0000-000000000001', 'f0000000-0000-0000-0000-000000000004', 'g0000000-0000-0000-0000-000000000004', 'Borderline compliance score (45/100) with validator disagreement (60% agreement). Internal Slack message with tone violations needs human judgment on whether internal communications require the same standards as external.', 'open');

-- Audit logs
INSERT INTO audit_logs (org_id, user_id, action, resource_type, resource_id, details) VALUES
  ('b0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', 'org_created', 'organization', 'b0000000-0000-0000-0000-000000000001', '{"name": "Acme AI Corp"}'),
  ('b0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', 'policy_created', 'policy', 'c0000000-0000-0000-0000-000000000001', '{"name": "Data Protection Policy"}'),
  ('b0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', 'policy_activated', 'policy', 'c0000000-0000-0000-0000-000000000001', '{"version": 1}'),
  ('b0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', 'agent_registered', 'agent', 'e0000000-0000-0000-0000-000000000001', '{"name": "Customer Support Bot", "type": "chatbot"}'),
  ('b0000000-0000-0000-0000-000000000001', NULL, 'validation_completed', 'validation', 'f0000000-0000-0000-0000-000000000001', '{"verdict": "approved", "compliance_score": 92}'),
  ('b0000000-0000-0000-0000-000000000001', NULL, 'validation_completed', 'validation', 'f0000000-0000-0000-0000-000000000002', '{"verdict": "rejected", "compliance_score": 12}'),
  ('b0000000-0000-0000-0000-000000000001', NULL, 'escalation_created', 'escalation', NULL, '{"request_id": "f0000000-0000-0000-0000-000000000004", "reason": "Borderline compliance"}');

-- Risk snapshot (today)
INSERT INTO risk_snapshots (org_id, agent_id, snapshot_date, total_validations, approved_count, rejected_count, escalated_count, avg_compliance_score, avg_risk_score) VALUES
  ('b0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001', CURRENT_DATE, 3, 1, 1, 1, 49.67, 55.00),
  ('b0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000002', CURRENT_DATE, 1, 1, 0, 0, 78.00, 30.00),
  ('b0000000-0000-0000-0000-000000000001', NULL, CURRENT_DATE, 4, 2, 1, 1, 56.75, 48.75);
